services:
  ghost:
    container_name: zachtaiji-com-blog
    image: ghost:latest
    restart: always
    ports:
      - "8080:2368"
    env_file:
      - ./env/ghost.env
    volumes:
      - ./ghost:/var/lib/ghost/content
  db:
    image: mysql:8.0.31
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
