services:
  ghost:
    container_name: zachtaiji-com-blog
    image: ghost:latest
    restart: always
    depends_on:
      - db
    volumes:
      - ./ghost:/var/lib/ghost/content:rw
    links:
      - db
    env_file:
      - env/ghost.env
    expose:
      - 2368
    ports:
      - 2368
    networks:
      - reverse-proxynet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`zachtaiji.com`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls.certresolver=myresolver"
      - traefik.http.services.ghost.loadbalancer.server.port=2368
  db:
    image: mysql:8.0.31
    restart: always
    env_file:
      - env/mysql.env    
    volumes:
      - ./mysql:/var/lib/mysql:rw
    networks:
      - reverse-proxynet
    expose:
      - 3306
networks:
  reverse-proxynet:
    name: reverse-proxynet
    external: true