services:
   index-test:
    container_name: zachtaiji-com-test
    image: nginx:latest
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST="zachtaiji.com"
      - VIRTUAL_PORT="80:80"
      - LETSENCRYPT_HOST="zachtaiji.com"
      - LETSENCRYPT_EMAIL="zach@steelhead.design"
    expose:
      - "443:443"
      - "80:80"